# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2018, 2, 19, 17, 19, 15, 32300)),
        ),
    ]
